//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jaejaeBoardASP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class jaejaeSystemEntities : DbContext
    {
        public jaejaeSystemEntities()
            : base("name=jaejaeSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCommonCode> tCommonCode { get; set; }
        public virtual DbSet<tCommonCodeGroup> tCommonCodeGroup { get; set; }
        public virtual DbSet<userTB> userTB { get; set; }
    
        public virtual ObjectResult<pSelectConditionTestTB_Result> pSelectConditionTestTB(string strSearchText)
        {
            var strSearchTextParameter = strSearchText != null ?
                new ObjectParameter("strSearchText", strSearchText) :
                new ObjectParameter("strSearchText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pSelectConditionTestTB_Result>("pSelectConditionTestTB", strSearchTextParameter);
        }
    }
}
