CREATE TABLE `jeckjeck`.`com_user` (
  `UIDX` INT NOT NULL,
  `USERID` VARCHAR(100) NULL,
  `USERPWD` VARCHAR(4000) NULL,
  `USERNM` VARCHAR(100) NULL,
  `USERTYPECD` VARCHAR(45) NULL,
  `GENDERCD` VARCHAR(45) NULL,
  `APPDT` VARCHAR(16) NULL,
  `APPTYPE` VARCHAR(45) NULL,
  `APPUSERID` VARCHAR(45) NULL,
  `DELYN` VARCHAR(2) NULL,
  `CREDT` VARCHAR(16) NULL,
  `CREUSERID` VARCHAR(45) NULL,
  `MODDT` VARCHAR(16) NULL,
  `MODUSERID` VARCHAR(45) NULL,
  PRIMARY KEY (`UIDX`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


CREATE TABLE [dbo].[COM_CODE_MST](
	[GROUPCD] [nvarchar](50) NOT NULL,
	[GROUPNM] [nvarchar](100) NOT NULL,
	[REMARK] [nvarchar](500) NULL,
	[DELYN] [nchar](1) NULL,
	[CREDT] [datetime] NULL,
	[CREUSERID] [nvarchar](20) NULL,
	[MODDT] [datetime] NULL,
	[MODUSERID] [nvarchar](20) NULL,
 CONSTRAINT [COM_CODE_MST_PK] PRIMARY KEY CLUSTERED 
(
	[GROUPCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[COM_CODE_LST](
	[DETAILCD] [nvarchar](20) NOT NULL,
	[GROUPCD] [nvarchar](50) NOT NULL,
	[DETAILCDNM] [nvarchar](2000) NOT NULL,
	[ORDERNO] [numeric](38, 0) NOT NULL,
	[VALUE1] [nvarchar](200) NULL,
	[VALUE2] [nvarchar](200) NULL,
	[VALUE3] [nvarchar](200) NULL,
	[VALUE4] [nvarchar](200) NULL,
	[VALUE5] [nvarchar](200) NULL,
	[DELYN] [nchar](1) NULL,
	[CREDT] [datetime] NULL,
	[CREUSERID] [nvarchar](20) NULL,
	[MODDT] [datetime2](0) NULL,
	[MODUSERID] [nvarchar](20) NULL,
	[REMARK] [nvarchar](max) NULL,
 CONSTRAINT [COM_CODE_LST_PK] PRIMARY KEY CLUSTERED 
(
	[GROUPCD] ASC,
	[DETAILCD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[COM_BOARD](
	[BOARDIDX] [numeric](38, 0) IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](100) NULL,
	[CONTENTS] [text] NULL,
	[DELYN] [nchar](1) NOT NULL,
	[CREDT] [datetime] NOT NULL,
	[CREUSERID] [nvarchar](20) NOT NULL,
	[MODDT] [datetime] NOT NULL,
	[MODUSERID] [nvarchar](20) NOT NULL,
 CONSTRAINT [COM_BOARD_PK] PRIMARY KEY CLUSTERED 
(
	[BOARDIDX] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
